import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {dependency,args,helpers} from './runtime.mjs';
process.env.RUNTIME_NODE_MODULES ||= process.env.ASF_RUNTIME_NODE_MODULES || (process.env.NODE_PATH||'').split(path.delimiter)[0];
const cli=args(),source=cli.input,output=cli['output-dir'];if(!source||!output)throw Error('Usage: smoke.mjs --input DECK.pptx --output-dir WORK');
const {PresentationFile,FileBlob}=await dependency('@oai/artifact-tool');
await fs.mkdir(output,{recursive:true});const p=await PresentationFile.importPptx(await FileBlob.load(source));
const before=await p.inspect({kind:'textbox,table,chart,shape',maxChars:1000000});await fs.writeFile(path.join(output,'before.ndjson'),before.ndjson);
const records=before.ndjson.split('\n').filter(Boolean).map(l=>JSON.parse(l));
const tb=records.find(x=>String(x.id||'').startsWith('tb/')),ch=records.find(x=>String(x.id||'').startsWith('ch/'));
// Only ids read from actual imported inspect output may be used.
const text=records.find(x=>String(x.id||'').startsWith('sh/')&&(x.text||x.textPreview));
if(!tb||!ch||!text)throw Error('Required imported editable objects absent');
const target=p.resolve(text.id);target.text='Edited template text';
p.resolve(tb.id).cells.set(1,1,'Edited evidence');
p.resolve(ch.id).series.getItemAt(0).values=[77,66,55];
const node=records.find(x=>x.slide===6&&String(x.name||'').startsWith('node-'));
if(!node)throw Error('Native diagram node absent');
p.resolve(node.id).position={left:node.bbox[0]+8,top:node.bbox[1],width:node.bbox[2],height:node.bbox[3]};
const raw=path.resolve(output,'edited-raw.pptx'),candidate=path.resolve(output,'edited-candidate.pptx'),file=path.resolve(output,'output/edited-saved.pptx');await(await PresentationFile.exportPptx(p)).save(raw);
execFileSync(process.env.RUNTIME_PYTHON||'python3',[fileURLToPath(new URL('restore_chart_workbook.py',import.meta.url)),source,raw,candidate]);
await fs.mkdir(path.dirname(file),{recursive:true});
const {finalizePresentation}=await helpers();
await finalizePresentation({workspaceDir:path.resolve(output),candidatePath:candidate,finalPath:file,pythonExecutable:process.env.RUNTIME_PYTHON||'python3',integrityValidatorPath:path.join(process.env.PRESENTATIONS_SKILL_DIR,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(process.env.PRESENTATIONS_SKILL_DIR,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--require-native-table-slide','5'],explicitTotalSlideCount:12,requiredNativeTableOwnerSlides:[5],requiredNativeChartOwnerSlides:[4],materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.resolve(output,'validation.json')});
const reopened=await PresentationFile.importPptx(await FileBlob.load(file));const after=await reopened.inspect({kind:'textbox,table,chart,shape',maxChars:1000000});await fs.writeFile(path.join(output,'after.ndjson'),after.ndjson);
const tableRecord=after.ndjson.split('\n').filter(Boolean).map(x=>JSON.parse(x)).find(x=>String(x.id||'').startsWith('tb/'));
const chartRecord=after.ndjson.split('\n').filter(Boolean).map(x=>JSON.parse(x)).find(x=>String(x.id||'').startsWith('ch/'));
const cellValue=reopened.resolve(tableRecord.id).getCell(1,1).value;
const chartValues=reopened.resolve(chartRecord.id).series.getItemAt(0).values;
if(!after.ndjson.includes('Edited template text')||String(cellValue)!=='Edited evidence'||JSON.stringify(chartValues)!==JSON.stringify([77,66,55]))throw Error(`Edits lost: ${cellValue} / ${JSON.stringify(chartValues)}`);
const nodeAfter=after.ndjson.split('\n').filter(Boolean).map(x=>JSON.parse(x)).find(x=>x.slide===6&&x.name===node.name);
if(!nodeAfter||Math.abs(nodeAfter.bbox[0]-node.bbox[0]-8)>.1)throw Error('Diagram position edit lost');
await fs.writeFile(path.join(output,'result.json'),JSON.stringify({application:'@oai/artifact-tool',textEdited:true,tableEdited:true,chartEdited:true,diagramNodeEdited:true,embeddedChartWorkbookValidated:true,saveReopen:true,officeClaim:false},null,2));
console.log(file);
